version: '3'

services:
  postgres:
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: developmentpassword
      POSTGRES_DB: developmentdb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "developmentdb"]

  drf-app:
    container_name: dev-drf-running-app
    build: 
      target: development
    volumes:
      - ./VotingSystem:/app
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations --settings=VotingSystem.settings.development && python manage.py migrate --settings=VotingSystem.settings.development && python manage.py runserver 0.0.0.0:8000 --settings=VotingSystem.settings.development"

volumes:
  postgres_dev_data: