version: '3'

services:
  postgres:
    container_name: drf-postgres
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  drf-app:
    build: . 
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
